### ISSUE TITLE
 No such file or directory: 'dsr_zs.npy'

### ISSUE THREAD

**Issue by QirenSun** [PhyllisH/NMP#2]
I was attempting to run the train_vrd.py, but I didn't have the dsr_zs.npy or zeroshot_vg.npz file in eval_metrics. Can you upload these files?

**Comment by QirenSun** [comment]
The code worked when I eliminated the datasets.

**Comment by afaq-ahmad** [comment]
Hi, can you forward me the code files, that how did you manage it,thanks

**Comment by afaq-ahmad** [comment]
How you eliminated the dataset

**Comment by YuxuanHe04** [comment]
Hi, I met the same error. Could you show me how to eliminate the datasets?
